"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Slice',
 'project_name': 'Agent Bazaar Hooks',
 'track': 'Slice',
 'pitch': 'An agent storefront that models dynamic pricing, checkout policy, and '
          'identity-aware access for ENS and Locus-powered commerce.',
 'idea_titles': ['ENS + Locus Commerce Store',
                 'Dynamic Agent Pricing Hooks',
                 'ERC-8128 Web Auth Checkout'],
 'architecture_summary': 'An agent storefront models dynamic pricing, checkout policy, '
                         'and identity-aware access. The contract stores pricing rule '
                         'hashes and merchant policy state, while Python scripts '
                         'assemble hook configurations and buyer flows.',
 'overlap_targets': ['PayWithLocus',
                     'ENS',
                     'Lido stETH Treasury',
                     'Virtuals',
                     'ERC-8004 Receipts',
                     'Celo'],
 'primary_contract_name': 'SliceHookController',
 'primary_python_module': 'slice_bazaar',
 'category': 'commerce',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'catalog_state',
                       'description': 'Inventory, hook configuration, and storefront '
                                      'settings.'},
                      {'name': 'buyer_identity',
                       'description': 'ENS, ERC-8004, or account-gating inputs.'},
                      {'name': 'checkout_route',
                       'description': 'Payment, discount, and settlement options.'},
                      {'name': 'receipts',
                       'description': 'Order confirmations and proof anchors.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for SliceHookController.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'slice_bazaar.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Slice',
               'docs_url': 'https://docs.slice.so/',
               'env_vars': ['SLICE_API_KEY', 'SLICE_HOOK_URL'],
               'endpoint_env': 'SLICE_HOOK_URL',
               'action_kind': 'rest_json',
               'purpose': 'Drive checkout hooks and storefront policy changes.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'},
              {'name': 'Virtuals',
               'docs_url': 'https://www.virtuals.io/',
               'env_vars': ['VIRTUALS_API_URL'],
               'endpoint_env': 'VIRTUALS_API_URL',
               'action_kind': 'rest_json',
               'purpose': 'Sync agent personas and commerce-facing identity metadata.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Celo',
               'docs_url': 'https://docs.celo.org/',
               'env_vars': ['CELO_RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Settle stablecoin-native transfers on Celo rails.'}],
 'actions': [{'id': 'slice_checkout_hook',
              'target': 'slice',
              'purpose': 'Use Slice for a bounded action in this repo.',
              'partner': 'Slice',
              'action_kind': 'rest_json',
              'max_amount_usd': 35,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Slice only after a dry-run artifact exists.',
                        'Use https://docs.slice.so/ for credential setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 90,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'virtuals_identity_sync',
              'target': 'virtuals',
              'purpose': 'Use Virtuals for a bounded action in this repo.',
              'partner': 'Virtuals',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call Virtuals only after a dry-run artifact exists.',
                        'Use https://www.virtuals.io/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'celo_payment_settle',
              'target': 'celo',
              'purpose': 'Use Celo for a bounded action in this repo.',
              'partner': 'Celo',
              'action_kind': 'contract_call',
              'max_amount_usd': 150,
              'priority': 70,
              'sensitivity': 'low',
              'notes': ['Call Celo only after a dry-run artifact exists.',
                        'Use https://docs.celo.org/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
